### ISSUE TITLE
downloaded ebook location?

### ISSUE THREAD

**Issue by Vansick1** [michaelnmmeyer/gutenberg#3]
I'm having some difficulty locating the individual ebooks that the script downloaded. I did find the database file; are the ebooks wrapped inside it, or are they simply referenced inside the database and the actual files are elsewhere? If they are inside the database file, is there a way I can modify the script so it downloads the ebooks into a directory so I can do with them as I please?

**Comment by michaelnmmeyer** [comment]
Hello,

Everything is stored within the database file. The ebooks you downloaded are stored in the `Data` table. To extract them all, you can use something like this (from your home directory):

```
import sqlite3, zlib

conn = sqlite3.connect(".gutenberg")
for key, data in conn.execute("select key, contents from Data"):
	text = zlib.decompress(data)
	with open("%s.txt" % key, "wb") as f:
		f.write(text)
```

If you want to download ebooks somewhere else, you need to modify the code here: https://github.com/michaelnmmeyer/gutenberg/blob/e83339d58b2eed877927be217fe0eee8017556ab/gutenberg.py#L772

Basically, replace...
```
cur.execute("""INSERT OR REPLACE
INTO Data(key, contents, url, last_modified, when_downloaded)
VALUES(?, ?, ?, ?, datetime('now'))""", data)
```

... with something like:
```
key, contents, url, last_modified = data
cur.execute("""INSERT OR REPLACE
INTO Data(key, contents, url, last_modified, when_downloaded)
VALUES(?, '', ?, ?, datetime('now'))""", (key, url, last_modified))
with open("%s.txt" % key, "wb") as f:
	f.write(zlib.decompress(contents))
```

**Comment by Vansick1** [comment]
How would I go about saving each book as their actual title and not their key value? I'm not terribly familiar with SQL

**Comment by michaelnmmeyer** [comment]
You need to join the Data and Metadata table. Something like:

```
import sqlite3, zlib, json

conn = sqlite3.connect(".gutenberg")
for meta, text in conn.execute("select metadata, contents from Data natural join Metadata"):
	meta = json.loads(meta)
	text = zlib.decompress(text)
	with open("%s.txt" % " ".join(meta["title"]), "wb") as f:
		f.write(text)
```

But then several ebooks might have the same title, so you need to sort that out by adding the ebook key, the authors names, etc.
